export const constants = {
    //Auth Actions
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

    LOGOUT: "USERS_LOGOUT",


    //User Actions

    UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",

    JWT_REQUEST: "JWT_REQUEST",
    
    //Post Actions

};